version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:dubnium
      - image: circleci/mongo:jessie

commands:
  prepare:
    steps:
      - checkout
      - run: sudo apt-get install mongodb-clients
      - run: ls modules/*/package.json | xargs -n1 md5sum > deps.txt
      - run: sudo npm i -g npm@6.13.4
      - run:
          # https://yarnpkg.com/en/docs/install#alternatives-stable
          name: Install Yarn@1.21.1
          command: |
            sudo unlink $(which yarn)
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
            echo "export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH" >> $BASH_ENV
      - run:
          name: Display version of Node.js, npm, Yarn and mongodb
          command: |
            node -v
            npm -v
            yarn --version
            mongo --version
  release:
    parameters:
      release_type:
        type: enum
        enum: ["patch", "minor"]
    steps:
      - add-ssh-keys:
          fingerprints:
            - "91:cd:e2:f6:96:ea:e5:9d:40:5b:b2:9a:b0:2c:ee:69"
      - run:
          name: Setup git
          command: |
            git config --global user.email "phenyl.js@gmail.com"
            git config --global user.name "phenyl-bot"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            npm whoami
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ .Branch }}-{{ checksum "deps.txt" }}
      - run:
          name: Clean tmp files
          command: yarn clean-tmp
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Publish packages
          command: yarn publish << parameters.release_type >> --yes

jobs:
  test:
    executor:
      name: default
    steps:
      - prepare
      - run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm whoami
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ .Branch }}-{{ checksum "deps.txt" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            # FIXME Add all node_modules in submodules
            - modules/phenyl-interfaces/node_modules
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ .Branch }}-{{ checksum "deps.txt" }}
      - run: yarn bootstrap
      - run: yarn build
      - run: yarn lint
      - run: yarn type-check
      - run: yarn test
  release_patch:
    executor:
      name: default
    steps:
      - prepare
      - release:
          release_type: "patch"
  release_minor:
    executor:
      name: default
    steps:
      - prepare
      - release:
          release_type: "minor"

workflows:
  version: 2.1
  test_deploy:
    jobs:
      - test
      - release_patch:
          type: approval
          filters:
            branches:
              only:
                - master
          requires:
            - test
      - release_minor:
          type: approval
          filters:
            branches:
              only:
                - master
          requires:
            - test
